### ISSUE TITLE
`inst` is undefined in _render loop

### ISSUE THREAD

**Issue by bedeoverend** [MeTaNoV/dom-repeat-n#4]
Seems that `_render` is sometimes being called with `_instances` not being of the same length as `this.count`, which causes the `inst` variable inside the loop to be undefined.

Either patching render to loop over `_instances` instead, or patching being called while `_instances` is out of parity with `count` should do the trick.

**Comment by bedeoverend** [comment]
Thanks @MeTaNoV - if possible, could you do a patch release? Without this commit can't use it in production. Apologies for not having a better repro for this bug as well.

**Comment by GeoloeG-IsT** [comment]
oh yeah, sorry, I do the release too!
