### ISSUE TITLE
TypeError when reducing the count to less than half

### ISSUE THREAD

**Issue by SPessall** [MeTaNoV/dom-repeat-n#6]
The 'dom-repeat-n' template causes a TypeError when reducing the count by a large amount (e.g. from 4 to 1).

> polymer-mini.html:2046 Uncaught TypeError: Cannot read property '_children' of undefined(…)_detachInstance @ dom-repeat-n.html:172

The problem is that method '_countChanged' iterates over the 'instances' array while at the same time removing values from it. This fails when removing more than half of the entries as the length of the array is then lower than the used index.

I managed to locally fix this problem by reversing the order, in which the iteration is performed. I replace the following line:

`for (i=newCount; i<limit; i++) {`

with

`for (i=limit-1; i>newCount-1; i--) {`

**Comment by GeoloeG-IsT** [comment]
sorry for the delay...
